# Generated by Django 5.1.2 on 2024-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "ordering": ["-date_posted"],
            },
        ),
    ]
